### ISSUE TITLE
Possible error of initializing "hasInitialAuth" value in src/app/App.tsx

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-drive#1]
I guess this function should return the opposite value (like `!window.location.pathname.startsWith('/urls')`, notice `!` at the beginning):

https://github.com/ProtonMail/proton-drive/blob/95cee5d6362748ef2f16eb6e3630c181dcc1df0c/src/app/App.tsx#L34-L36

What makes me to think so:
- Right now it asks me to sign in even if I have valid `cookies + window.name` values set. Other apps, like contacts/settings/etc properly pick-up/detect the valid session but not the `drive` app.
- Later the public app gets loades for `/urls` route:
https://github.com/ProtonMail/proton-drive/blob/95cee5d6362748ef2f16eb6e3630c181dcc1df0c/src/app/App.tsx#L42-L46

**Comment by mmso** [comment]
Thanks for the report @vladimiry 

This will be fixed in an upcoming release

**Comment by vladimiry** [comment]
@mms, a quick question regarding drive. Will it be fully functional if there is no support for Service Worker in the browser?

**Comment by vincaslt** [comment]
> @mms, a quick question regarding drive. Will it be fully functional if there is no support for Service Workers feature in the browser?

In a sense, yes, but it will be left at a mercy of the OS. Service worker is used to mitigate memory loads during download, and if it's unavailable, the download will proceed fully in-memory, which could fail with very large files if there's not enough memory or OS decides to kill the process.

**Comment by vladimiry** [comment]
@vincaslt thanks for the detailed response. In ElectronMail app I intentionally use in-memory only storage for the email account webviews (non of the browser-specific storages get written to disk) which means the absence of Service Workers support5 won't make any difference in my case.

**Comment by vladimiry** [comment]
Handled in 1503d9034fde2f791e1a79c87795e535fec504e7.
