### ISSUE TITLE
The code of deployed client version is not publihsed here

### ISSUE THREAD

**Issue by vladimiry** [ProtonMail/proton-drive#10]
Currently deployed on https://drive.protonmail.com/ version: 4.1.23 / 52987e2e59888423f338f04e31f94ae1c5cc0cf6

Published code (here in https://github.com/ProtonMail/proton-drive): v4.1.18 / 0631ebfc1e0fba30b046c8fc8074d73c69d088c2.

**Comment by dhoko** [comment]
Woops, voilà https://github.com/ProtonMail/proton-drive/releases/tag/v4.1.23 :)

**Comment by vladimiry** [comment]
Thanks :thumbsup:
