### ISSUE TITLE
Translation location?

### ISSUE THREAD

**Issue by sysadt** [ProtonMail/proton-drive#2]
Hi,
sorry for the possibly dumb question but could you please link the ProtonDrive crowdin project? I could not find it there.
Or if translation is done in this repo, could you please show me the folder path?

I found something where the translation could be better.
Thanks.

**Comment by dhoko** [comment]
:wave: 

voilà  https://crowdin.com/project/protonmail 
Yep,  we need to add the link inside the readme.
